libreoffice: add `java.logging` to minimal JRE
This is e.g. required to properly use the Langtool-plugin[1] which
otherwise fails like this:

    java.lang.NoClassDefFoundError: java/util/logging/Logger

Fixes #160315

[1] https://extensions.libreoffice.org/en/extensions/show/languagetool

(cherry picked from commit b308b06c22566a68308328b8c43509b72b1b9172)