chromiumBeta: Fix a compilation error
LLVM 14 doesn't support those build flags yet
(-no-opaque-pointers is the argument for -Xclang):
error: unknown argument: '-no-opaque-pointers'

Those build flags were added in the following commit:
https://source.chromium.org/chromium/chromium/src/+/003067c130958bb2f867324cd675b4e5d1efbf00

(cherry picked from commit 7f684c2ba0a35ecdee3c1dcc5fb15e0fcb4be581)