Fix eval with `nix-env -qas`
At least on NixOS, it fails to evaluate as follows:

	$ nix-env -qaPs -f .
	error: attribute '__propagatedImpureHostDeps' missing

(cherry picked from commit b8c07facaa578c05af95fb4b2479bdfd9a433e31)